apiVersion: v1
kind: Service
metadata:
       name: rabbitmqServer
       labels:
               app: rabbitmq
spec:
       type: ClusterIP
       selector:
               app: rabbitmq
       ports:
               - name: tcp1
                 port: 5672
                 targetPort: 5672
               - name: tcp2
                 port: 15672
                 targetPort: 15672
