apiVersion: v1
kind: PersistentVolumeClaim
metadata:
        name: persistencia
spec:
        accessModes:
                - ReadWriteOnce
        resources:
                requests:
                        storage: 5Gi
