apiVersion: v1
kind: Service
metadata:
        name: rabbitmq
        labels:
                service: rabbitmq
spec:
        type: ClusterIP
        selector:
                service: rabbitmq
        ports:
                - name: tcp1
                  port: 5672
                  targetPort: 5672
                - name: tcp2
                  port: 15672
                  targetPort: 15672